### ISSUE TITLE
Not working in 1.19.4 paper

### ISSUE THREAD

**Issue by FC-Creations** [xtkq-is-not-available/VoidGen#7]
I run this command:
/mv create WorldName normal -t FLAT -g VoidGen

I get error: No key layers in MapLike[{}]

And when the world generates, it's just a normal vanilla generated world. 

Helpful note, I got a similar error while I was setting up the default world in server.properties.  

Normally this would be the json: {"settings"\:{"biome"\:"minecraft\:plains","layers"\:[]}}

But now to get it to work I have to use this json instead: {"biome"\:"minecraft\:plains","layers"\:[]}

Not sure if that's relevant or helpful, but figured I'd mention it anyway!

**Comment by ThatSoulyGuy** [comment]
Development has been cancelled for years
